### ISSUE TITLE
State is mapped multiple times with same value.

### ISSUE THREAD

**Issue by ilazarte** [angular-redux/ng-redux#107]
I'm not sure if this is a redux thing or ng-redux thing.

In the counter demo I added a simple logging statement to mapStateToThis:  
console.log("mapStateToThis: ", state);

If you press increment in the ui and watch the console logs, eventually the console.log statements will start appearing twice identically.  

This is happening on a clone of master as of two days ago.

**Comment by deini** [comment]
1-year later reply :(

This is related to https://github.com/gaearon/redux-devtools/issues/32 which is not an issue just how devtools work, shouldn't affect your state.
