### ISSUE TITLE
How to use redux-persist together with ng-redux?

### ISSUE THREAD

**Issue by neyromant** [angular-redux/ng-redux#109]
Can you please tell how to use redux-persist together with ng-redux?
Or, if this is not possible, advise a way to save and restore the state to localstorage or indexeddb.

Thank you in advance and look forward to the answer.

**Comment by matt-sanders** [comment]
http://stackoverflow.com/questions/39992711/how-to-use-ng-redux-redux-persist/40415140#40415140
