### ISSUE TITLE
Current version is not released.

### ISSUE THREAD

**Issue by bopm** [angular-redux/ng-redux#113]
3.3.0 was released back in January and current API and codebase changed a lot. For example `createStoreWith` now taking an object as a reducer. Please release 3.4.0 to provide access to these changes for version strict environments (like rails-assets.org for example).

**Comment by AntJanus** [comment]
Release cycle is back up and running! I created an issue tracking the latest updates on the roadmap: https://github.com/angular-redux/ng-redux/issues/142
