### ISSUE TITLE
Inject angular services to action creators?

### ISSUE THREAD

**Issue by zalishchuk** [angular-redux/ng-redux#116]
Any ideas how to inject angular services like `$http` or `$q` to use in Redux action creators? Now I am using [third-party library](//github.com/mzabriskie/axios) to make HTTP requests. Using this action creator as angular service is unsuitable for me, because action creator can be called from non-angular conditions. My bad, if the answer already exists.

Now my action creators looks like this:
```js
export function fetchContentItems(value) {
  return (dispatch) => {
    dispatch(requestContentItems());

    return axios(API_URL)
      .then(({ data }) => {
        dispatch(setContentCount(data.count));
        dispatch(receiveContentItems(data.items));
      });
  };
}
```

Non-angular conditions I talked about before:
```js
export function setFilterOption(option, value) {
  return (dispatch, getState) => {
    dispatch({
      type: SET_FILTER_OPTION,
      option,
      value
    });

    const { filter: { options } } = getState();

    dispatch(fetchContentItems(options));
  };
}
```

**Comment by zack9433** [comment]
Action could be wrapped in `angular.facory` or simply use `angular.element(document.body).injector().get('$http')`

**Comment by zalishchuk** [comment]
@zack9433 I can inject any kind of services like `$location` using this code?

**Comment by zack9433** [comment]
@zalishchuk sure, you can test it in the console. http://stackoverflow.com/questions/15527832/how-can-i-test-an-angularjs-service-from-the-console

**Comment by zalishchuk** [comment]
@zack9433 are you sure it's not an anti-pattern in angular, huh?

**Comment by rileylnapier** [comment]
Use middleware?

**Comment by wbuchwalter** [comment]
Any reason you can't do like in the [example](https://github.com/angular-redux/ng-redux/blob/master/examples/async/actions/asyncService.js#L33)?
Am I missing something in your question?
