### ISSUE TITLE
Current DevTools Example Throws TypeError: this.$eval is not a function at $apply

### ISSUE THREAD

**Issue by ClayChristmas** [angular-redux/ng-redux#117]
The current Redux-DevTools example in the readme file throws the following exception whenever a new state occurs: TypeError: this.$eval is not a function.  Removing the $rootScope.$apply call fixes this exception from occurring.

**Comment by zoamel** [comment]
Same error in my case, unfortunately removing $rootScope.$apply brokes app refreshment when playing with redux dev tools

**Comment by ClayChristmas** [comment]
I figured out a fix this morning for this.  I'm planning on doing a PR with a fix for it as well as some other info on using the chrome devtools extension instead of including react and everything in your app.  The devtools extension is way better than the embedded one that is currently being used.

The fix to stop the $eval errors from the console is to pass a function to the call to $apply.  Here is what the new code looks like:
`$ngRedux.subscribe(() => {
            $timeout(() => {$rootScope.$apply(() => {})}, 100);
        });`

**Comment by ClayChristmas** [comment]
PR Created [here](https://github.com/angular-redux/ng-redux/pull/118) that includes the fix and shows how to use Redux DevTools Extension instead of the npm package.  The extension provides more functionality and can sit in the chrome dev tools under a tab or be docked, so it doesn't compete with your screen realestate.

**Comment by wbuchwalter** [comment]
Thanks!
