### ISSUE TITLE
Bower package outdated

### ISSUE THREAD

**Issue by VolleMelk** [angular-redux/ng-redux#124]
The bower package is outdated and it took me forever to figure that out.

```
bower ng-redux#*              mismatch Version declared in the json (3.1.0) is different than the resolved one (3.3.0)
bower ng-redux#*              resolved https://github.com/wbuchwalter/ng-redux.git#3.3.0
bower ng-redux#^3.3.0          install ng-redux#3.3.0

ng-redux#3.3.0 bower_components\ng-redux
```

The examples on the front page are not working (reducers are only allowed to be of type Function) and thus precious development time is forever lost and cannot be retrieved except when sacrificing (already) rare family time.

So, pretty please, don't forget us bower users :)

**Comment by AntJanus** [comment]
@VolleMelk we deprecated bower support after v3.5.2
