### ISSUE TITLE
How to use guards with redux?

### ISSUE THREAD

**Issue by leroy-buchholz** [angular-redux/ng-redux#131]
I want to hide all pages exept the sign-in-page of my app for unauthenticated users. In an angular project without redux i used guards. Is there a best practice or another workaround with ng-redux?

**Comment by Kepro** [comment]
use StackOverflow to ask questions....

**Comment by leroy-buchholz** [comment]
Talk to a wall to give useless comments...

**Comment by Kepro** [comment]
your question is not for ng-redux and it's not an issue, so UTFG :)

**Comment by AntJanus** [comment]
@leroy-buchholz Not sure about the best practice but depending on your router, you can inject `ng-redux` into its resolve and check if the user is able to show up there. If not, you can reroute them. We use something similar at my company. Can you link me to guards? I'd love to read about it, maybe I can have better input

@Kepro it's not an issue, and we'll close this but I don't mind the discussion continuing here. I'd rather people open issues and discuss than drop `ng-redux` out of frustration even if it's a redux-only question.
