### ISSUE TITLE
Using Redux devtools extension cause error

### ISSUE THREAD

**Issue by Clebiez** [angular-redux/ng-redux#134]
Hi,

When I try to use Redux devtools chrome extension as I read on the readme, I get an error :
`Uncaught TypeError: t.apply is not a function
    at <anonymous>:3:3982
    at <anonymous>:3:422
    at <anonymous>:2:725
    at eval (webpack:///../app/~/redux/es/compose.js?:32:14)
    at Array.reduceRight (native)
    at eval (webpack:///../app/~/redux/es/compose.js?:31:17)
    at eval (webpack:///../app/~/redux/es/applyMiddleware.js?:43:100)
    at ngReduxProvider.$get (webpack:///../app/~/ng-redux/lib/components/ngRedux.js?:106:215)
    at Object.invoke (webpack:///../app/~/angular/angular.js?:5003:19)
    at eval (webpack:///../app/~/angular/angular.js?:4795:37)`

I create the store like this :

`const logger = createLogger({
        level: 'info',
        collapsed: true
    });
    $ngReduxProvider
        .createStoreWith(store, [logger, window.__REDUX_DEVTOOLS_EXTENSION__()]);
`

And in the app.run, I add too
`    $ngRedux.subscribe(() => {
        $timeout(() => {
            $rootScope.$apply();
        }, 100);
    });`

When I remove the devtool on the createStoreWith method, it works (but I want it :cry: )
Any idea ?

Regards

**Comment by whazap** [comment]
abit late, but try:
`createStoreWith(store, [logger], [window.__REDUX_DEVTOOLS_EXTENSION__()]);`

from the docs:
`createStoreWith(reducer, [middlewares], [storeEnhancers], [initialState])`

also, watch out, that will cause an error for users without the extension, so:
`createStoreWith(store, [logger], window.__REDUX_DEVTOOLS_EXTENSION__ ? [window.__REDUX_DEVTOOLS_EXTENSION__()] : null);`

**Comment by bayucandra** [comment]
I have a similar problem like this. My script looks like this:

`    angular.module('App')
        .config(function($ngReduxProvider){
            var reducer = Redux.combineReducers({
                dashboardPage: dashboard,
                mainMenu: mainMenu,
                headerBar: headerBar
            });
            $ngReduxProvider.createStoreWith(
              reducer
              ,window.__REDUX_DEVTOOLS_EXTENSION__ ? [window.__REDUX_DEVTOOLS_EXTENSION__()] : null
            );
        });`

And it gives me errors like this:

`vendor.min.js:1 Uncaught TypeError: t.apply is not a function
    at <anonymous>:1:47480
    at <anonymous>:1:33759
    at <anonymous>:1:26192
    at redux.js:714
    at redux.js:757
    at Object.createStore (redux.js:290)
    at Object.$get (vendor.min.js:18)
    at Object.invoke (vendor.min.js:7)
    at vendor.min.js:7
    at l (vendor.min.js:7)`

Any helps will be highly appreciated. Thanks in advance.
