### ISSUE TITLE
Create multiple stores

### ISSUE THREAD

**Issue by dwiyatci** [angular-redux/ng-redux#135]
Possibility? 🤔

**Comment by mblodorn** [comment]
"If you're coming from Flux, there is a single important difference you need to understand. Redux doesn't have a Dispatcher or support many stores. Instead, there is just a single store with a single root reducing function. " You can read more at: http://redux.js.org/docs/api/Store.html

**Comment by AntJanus** [comment]
@dwiyatci you *can* create multiple stores using vanilla Redux, you just can't bootstrap them together in a single AngularJS application and that's by design. Redux in React works the same way. You can also refer to @mblodorn 's comment.
