### ISSUE TITLE
Can't find variable: Symbol in node_modules/ng-redux/dist/ng-redux.js

### ISSUE THREAD

**Issue by raajamalik** [angular-redux/ng-redux#141]
Hello,

I am facing this issue while running testcases:

ReferenceError: Can't find variable: Symbol in node_modules/ng-redux/dist/ng-redux.js (line 1)

To be precise, it failed at the below highlighted line:
this.createStoreWith = function(o, i, c, a) {
           .....
           .....
        }, this.$get = function(o) {
            for (var u = void 0, i = [], a = n, f = Array.isArray(a), s = 0, a = f ? a : a[**Symbol.iterator**]();;) {

I see a, the fourth argument to createStoreWith function is INITIAL state, which is not being passed in testcases. May be that is why it is failing here. Do, we have to mock this to run the testcases?

Also, if I mock ngRedux like below, then the test case pass:

$provide.value('$ngRedux', {
                    subscribe: angular.noop,
                    getState: function() {
                        return {
                            property: {
                                loadedFiles: angular.noop,
                                properties: angular.noop
                            }
                        };
                    }
                });

Somehow, it is not identifying Symbol. It used to run earlier. Any help would be much appreciated.

**Comment by AntJanus** [comment]
Should be fixed right now.
