### ISSUE TITLE
3.4.0 release missing lib/index.js

### ISSUE THREAD

**Issue by maxlapides** [angular-redux/ng-redux#143]
In the npm 3.4.0 release, the package.json points `main` to `./lib/index.js`. This file does not exist, so my build is failing.

**Comment by AntJanus** [comment]
@maxlapides thanks! I see where I messed up. Apologies.

**Comment by maxlapides** [comment]
@AntJanus No problem! Thanks so much for taking on maintenance of this project, we really appreciate it!

**Comment by AntJanus** [comment]
@maxlapides sorry about that! I pushed a new version 3.4.1 which has the dist. Let me know if it works and I'll close the issue.

Phew. Glad for the quick response.

**Comment by maxlapides** [comment]
It works! Thanks for the quick fix :)
