### ISSUE TITLE
Passing an existing store to ng-redux

### ISSUE THREAD

**Issue by cmcguire79** [angular-redux/ng-redux#168]
Hi

I want to migrate my angular spa to a more progressive solution. As a part of this process I want to start extracting pieces from the application into isolated steps and then lazy loading the steps as required. I would like to create the redux store at the very top level and then pass it into each step or the angular app as required. Is it possible to pass an already created store to ng-redux?

Thanks
Cathal

**Comment by deini** [comment]
Hi Cathal,

Currently its not possible, however this feature is part of the [roadmap](https://github.com/angular-redux/ng-redux/issues/164).

Closing this as its a duplicate from https://github.com/angular-redux/ng-redux/issues/19. Thanks for letting us know there are more people interested in this feature.
