### ISSUE TITLE
Allow for custom angular binding

### ISSUE THREAD

**Issue by mnovinger** [angular-redux/ng-redux#169]
Hi, I was wondering if it would be feasible to allow for a custom angular binding. Right now index.js is attaching directly to angular.module, but we namespace angular to a custom variable. 

I tried this approach, but webpack warned it would break the default export, which is a non-starter. https://github.com/mnovinger/ng-redux/blob/master/src/index.js

**Comment by deini** [comment]
Is this something that can be done in your config with webpack's [provide plugin](https://webpack.js.org/plugins/provide-plugin/)?

**Comment by deini** [comment]
Closing this issue because it has been inactive for a while.
