### ISSUE TITLE
subscribe return type in INgRedux

### ISSUE THREAD

**Issue by dawidzq** [angular-redux/ng-redux#172]
Hello,

Is there any reason that the `subscribe()` function returns a Function in index.d.ts rather than type Unsubscribe (defined inside of 'redux')?

**Comment by AntJanus** [comment]
@dawidzq I'm not a type guru so I can't answer the question but if you feel like you can fix this issue, please open a PR. I'll merge it in and do a release.

**Comment by dawidzq** [comment]
@AntJanus I created a PR here: https://github.com/angular-redux/ng-redux/pull/173

Let me know if I did something wrong. This would be my first one. 😄

**Comment by AntJanus** [comment]
Thanks for the submission! It was merged in.
