### ISSUE TITLE
[Docs] StoreEnhancer link in readme 404s

### ISSUE THREAD

**Issue by Lknechtli** [angular-redux/ng-redux#174]
Under the API section: http://rackt.github.io/redux/docs/Glossary.html#store-enhancer - should probably link to https://github.com/reactjs/redux/blob/master/docs/Glossary.md#store-enhancer

**Comment by deini** [comment]
@Lknechtli mind doing a PR? 🙏

**Comment by AntJanus** [comment]
fixed.
