### ISSUE TITLE
Fix ES6 export in TypeScript definitions

### ISSUE THREAD

**Issue by smrq** [angular-redux/ng-redux#177]
This commit broke importing this module from TypeScript: https://github.com/angular-redux/ng-redux/commit/0f9fe1728fa43b1ab4946ee556d63ca754472421#diff-b52768974e6bc0faccb7d4b75b162c99

The following TypeScript code should work:
```
import ngRedux from 'ng-redux';
```

After this commit, which removes the default export from the typings, this fails with the following error:

```
error TS1192: Module '"/path/to/node_modules/ng-redux/index"' has no default export.
```

**Comment by ionutVizitiu** [comment]
Hi,

I think also that the whole commit should be reverted.
Is there any reason to keep it like this?

**Comment by cristianmartinez** [comment]
Same problem here.

**Comment by AntJanus** [comment]
I'll go ahead and merge that PR in.

**Comment by ionutVizitiu** [comment]
Thank you @AntJanus .
Any idea when you have some time for that?

**Comment by AntJanus** [comment]
@ionutVizitiu doing  4.0 release tonight.

**Comment by ionutVizitiu** [comment]
Thank you very much @AntJanus !
I appreciate your work.

**Comment by ionutVizitiu** [comment]
I've created this PR https://github.com/angular-redux/ng-redux/pull/192
