### ISSUE TITLE
4.1.0 Release

### ISSUE THREAD

**Issue by bjohnso5** [angular-redux/ng-redux#198]
Wondering if it's possible to have a 4.1.0 release prepared with the recently merged digest debounce changes included.

It's a feature my team is very excited about integrating into our application.

Cheers!

**Comment by AntJanus** [comment]
The issue in #196 is holding up a new release and I think none of the contributors (including me) have the bandwidth to tackle it. If either of you would like to contribute to the fix, even just getting it started and leaving it for someone else to finish, that would be appreciate and will speed up the publishing process.

**Comment by bjohnso5** [comment]
@AntJanus I'll see if I can dive into it sometime in the next couple of days

**Comment by piehouserat** [comment]
I know everyone is super busy but eagerly awaiting the next release that has the digest debouncing stuff. We've pretty much converted our whole app to use redux & ng-redux and while we are much happier with the state of the code and our ability to move to react fairly easily, the performance has suffered as we dispatch quite a lot of actions.

Is there any way to somehow get this code into my app ASAP - I don't suppose I can simply download a zip of the master branch and overwrite the contents of the ng-redux node_modules dir?

**Comment by AntJanus** [comment]
@piehouserat you could, you'd just have to make sure you compile it first. I can go ahead and release what we have under like a `4.1.0-alpha` release. Would that work? 

Honestly, we just need to fix that dev tools compat issue and I'm ready to release it. The other items on the release list #204 aren't as important. 

Closing this in favor of #204
