### ISSUE TITLE
types: `connect` should allow `null` as the first argument

### ISSUE THREAD

**Issue by no-stack-dub-sack** [angular-redux/ng-redux#200]
`connect` [appears to allow](https://github.com/angular-redux/ng-redux/blob/3eb5e42a056f9d01c7adecd7ed85c9262bb65bb4/src/components/connector.js#L16) a a null argument as the first argument, in the event that you only need to fire an action from a particular component, and do not need to map any state slices to your component's state. e.g.

```ts
constructor(public $ngRedux: ngRedux.INgRedux) {
  this.unsubscribe = $ngRedux.connect(null, componentActions)(this);
}
```

However, the types for `connect` are not written with an overload to support this. This forces you to write a `mapStateToThis` method that is ultimately not needed. It looks like there are some other changes holding up the 4.1.0 release, so this could be an easy fix to sneak in before that release. 

Will you accept a PR to fix this?

**Comment by no-stack-dub-sack** [comment]
@AntJanus do you happen to know who might be able to answer this for me? I'd love to make a contribution before the next release if I can (assuming this is something the team is interested in seeing).

**Comment by AntJanus** [comment]
@no-stack-dub-sack I'd accept a PR for it. It looks like the typing is a frequent issue and I don't have much knowledge about it.

**Comment by no-stack-dub-sack** [comment]
@AntJanus cool , thanks - I'll work something up in the next few days, and I'll take a look through the rest of the file to see if anything else jumps out at me while I'm at it.
