### ISSUE TITLE
Redux 4.0.0 is available

### ISSUE THREAD

**Issue by Lalem001** [angular-redux/ng-redux#203]
Currently this package has a peerDependency on `redux@^3.0.0`. Installing 4.0.0 causes a warning, but is otherwise compatible from my own testing. I have not tried ng-redux's own tests against it.

Any chance of updating the peerDependency to something like `^3.0.0 || ^4.0.0` if it passes all tests?

**Comment by JesseObrien** [comment]
Bump for annoyance 👍

**Comment by AntJanus** [comment]
I'm taking this on right now.
