### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by villesau** [angular-redux/ng-redux#220]
This pull request: https://github.com/angular-redux/ng-redux/pull/217 has been merged, but the new version is not released in NPM yet. This is required for us to get rid of the fork. Could you release the new version in NPM? Thank you!

**Comment by AntJanus** [comment]
Will do!

**Comment by AntJanus** [comment]
@villesau it's out under v4.4.0

**Comment by villesau** [comment]
Great, thanks a lot! :)
