### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by tsilen** [angular-redux/ng-redux#223]
Hi,

Could we have a new release (4.4.1) to get the already updated package.json in as this now depends on a vulnerable lodash version.

Thanks!

**Comment by leandrw** [comment]
There is something we should do before make the fix publicly available?

**Comment by leandrw** [comment]
I've sent an email message to evan@schultz.codes.
I hope he can help us.

**Comment by AntJanus** [comment]
I'll get on it.

**Comment by AntJanus** [comment]
I was moving and my old machine died so I missed this entire thing and didn't have NPM setup for publishing. The new version is out
