### ISSUE TITLE
Maintainer access

### ISSUE THREAD

**Issue by oliviernt** [angular-redux/ng-redux#238]
Hi,

I'm hereby requesting maintainer access to the repository. I had written directly to @AntJanus  on Twitter how asked me to fill an issue here on Github.

We're still using the ng-redux Library in a few of our legacy projects and need to keep the dependencies up to date. I've noticed that updates need some time to get through and I completely understand that this project is legacy and not in focus anymore.

As time is scarce I probably wouldn't do much more myself than chores like updating dependencies but I think this alone would benefit a few people.

Thank you.

Cheers,
Olivier

**Comment by eas604** [comment]
I hope someone can take on dependency chores so #234 can be addressed. :)

**Comment by AntJanus** [comment]
@oliviernt I sent you an invite to be a collaborator. Thanks for taking this on!

**Comment by oliviernt** [comment]
Thank you!

**Comment by oliviernt** [comment]
@AntJanus could I also get permissions to publish on npm please?

**Comment by AntJanus** [comment]
@oliviernt same username on NPM as here?

**Comment by oliviernt** [comment]
Oh, sorry fogot to mention that. Yes, it's also oliviernt

Le mar. 9 févr. 2021 à 23:20, Antonin Januska <notifications@github.com> a
écrit :

**Comment by AntJanus** [comment]
@oliviernt you've been added!

**Comment by oliviernt** [comment]
Thank you. I just published v4.4.2
