### ISSUE TITLE
Do not include Redux and other libs in bower component

### ISSUE THREAD

**Issue by Elijen** [angular-redux/ng-redux#70]
Currently the bower component includes Redux itself, lodash and other libraries which is making it quite large (~3000 lines vs ~800 lines that has the whole Redux lib). I think Redux should simply be stated as a dependency, not included in the component and the other dependencies should be removed.

**Comment by merqlove** [comment]
Hi, i did some workaround config.
https://github.com/merqlove/ng-redux/tree/extract-deps

**Comment by merqlove** [comment]
Result package is at ./dist/ng-redux.var.js
