### ISSUE TITLE
Use with .component syntax?

### ISSUE THREAD

**Issue by dmackerman** [angular-redux/ng-redux#80]
Is it possible to use this library with `.component` in Angular 1.5? I'm getting the error `warning.js:14 Store does not have a valid reducer. Make sure the argument passed to combineReducers is an object whose values are reducers.`, which seems odd. Here's some code

`home.component.js`

``` js
import * as PhotoActions from 'actions/photo.actions';
import template from './home.component.html';

class HomeController {
    constructor($ngRedux, $scope) {
        const unsubscribe = $ngRedux.connect(this.mapStateToThis, PhotoActions)(this);
        $scope.$on('$destroy', unsubscribe);
    }

    // Which part of the Redux global state does our component want to receive?
    mapStateToThis(state) {
        return {
            photos: state.photos
        };
    }
}

export const homeComponent = {
    template: template,
    controller: HomeController
};
```

This is attached to a module, `.component('homeComponent', homeComponent)`. All registers just fine, and if I remove the ngRedux code it renders fine.

I have a `photos.reducer`, which is exported using `combineReducers`:

``` js
import { LOAD_PHOTOS } from 'actions/photo.actions';

export default function photos(state = [], action) {
    switch (action.type) {
        case LOAD_PHOTOS:
            return action.payload;
        default:
            return state;
    }
}
```

...and then exported as `rootReducer` from `reducers/index.js` here.

``` js
import { combineReducers } from 'redux';
import photos from './photos.reducer';

const rootReducer = combineReducers({
    photos
});

export default rootReducer;
```

And in the config phase, I register everything.

``` js
import rootReducer from './reducers'
// ...
.config($ngReduxProvider => {
    $ngReduxProvider.createStoreWith(rootReducer, [loggerMiddleware]);
})
```

Am I doing something wrong, or can this library just not be used with `.component` and only `directive`?

**Comment by dmackerman** [comment]
Ok, so for whatever reason, it seems to have been a version thing. Everything works with the following versions:

```js
+    "angular": "^1.5.5",
+    "ng-redux": "^3.0.0",
+    "react-redux": "^4.0.1",
+    "redux": "^3.0.0",
+    "redux-devtools": "^3.0.0",
+    "redux-thunk": "^1.0.2"
```

Copied from the `counter` example.

**Comment by Negan1911** [comment]
Hey, i wrote a new featute for this one #121 for being more precise, stay tuned to see if someone reivews the pull request!
