### ISSUE TITLE
add initialState param to createStoreWith in index.d.ts

### ISSUE THREAD

**Issue by ipassynk** [angular-redux/ng-redux#83]
initialState param is missing in  createStoreWith in index.d.ts.

here is createStoreWith function:
this.createStoreWith = (reducer, middlewares, storeEnhancers, initialState)...

here is index.d.ts that does not include initialState param:
createStoreWith(reducer: Reducer, middlewares?: Array<Middleware | string>, storeEnhancers?: Function[]): void;

**Comment by AntJanus** [comment]
Looking at the file now, it looks like it was added last November and this issue never addressed. Closing this out. Thanks! :)
