### ISSUE TITLE
Change global .babelrc to local options

### ISSUE THREAD

**Issue by ZeeStorm** [angular-redux/ng-redux#84]
If you're using gulp with babel, and include all dependencies in a bundle (when not using browserify or webpack, for example), ng-redux causes an error due to the .babelrc global config file, which babel will read when processing all files.

If you're noticing this error:
Error: Couldn't find preset "es2015-loose" relative to directory "../node_modules/ng-redux"

To get around this bug, the easiest fix is to install `babel-preset-es2015-loose` in your project. The proper fix is for ng-redux to only include it locally, since the preset is a devDependency and not a dependency, and .babelrc is a global requirement.
Hopefully this helps a few people dealing with the same issue.

**Comment by AntJanus** [comment]
It looks like the preset was changed to `babel-preset-es2015-loose` at some point. Thanks for bringing this up!

:)
