### ISSUE TITLE
compare state and prevState

### ISSUE THREAD

**Issue by TrySound** [angular-redux/ng-redux#85]
There is an optimization in react-redux which compares previous and current state and do not make slice if they are equal. Is it possible to introduce this optimization in ng-redux?

**Comment by wbuchwalter** [comment]
Yes, I don't see why not.
Do you have a scenario where this optimization is useful? I have a hard time picturing slicing as a bottleneck (unless you have 1 mapStateToProps for the whole application, or that kind of bad practice maybe).

**Comment by TrySound** [comment]
@wbuchwalter A case is something like selecting already selected item, which shoudn't update state and force recalculating slice of same data.

**Comment by wbuchwalter** [comment]
My question was more about trying to figure out a scenario where what you said would *actually* cause perf issues.


But anyway, yes it should be easily doable.

 






On Fri, May 27, 2016 at 5:47 AM -0700, "Bogdan Chadkin" <notifications@github.com> wrote:












@wbuchwalter A case is something like selecting already selected item, which shoudn't update state and force recalculating slice of same data.

**Comment by TrySound** [comment]
There is not so big perf issue, but still props recalculating in tens components could be prevented, this will save a bit of memory I think.

**Comment by TrySound** [comment]
Also nothing will work if somebody will forget to mutate store, which can force to follow the most important rule of redux.

**Comment by AntJanus** [comment]
Added to 4.1.0 roadmap
