### ISSUE TITLE
onCompleted not working

### ISSUE THREAD

**Issue by sahlouls** [angular-redux/ng-redux#93]
Hi,

When, onCompleted is not called

![image](https://cloud.githubusercontent.com/assets/3117988/16736921/6b75457a-478f-11e6-9f99-09e6965a3154.png)

Any ideas why ?

Regards

**Comment by wbuchwalter** [comment]
Hey there,
You might want to post this issue on the [RxJS repo](https://github.com/Reactive-Extensions/RxJS) instead.
