### ISSUE TITLE
Initial Component State

### ISSUE THREAD

**Issue by JesterXL** [angular-redux/ng-redux#94]
Thanks for this awesome library! Question about initial component state.

My component's controller class (which is just a function):

```javascript
// SearchController
var vm = this;
vm.search = "";
vm.searchField = 'name';
vm.loading = false;
$ngRedux.connect(vm.mapStateToThis)(vm);
```

```javascript
// default state
{
   search: 'cow'
}
```

After I login, I got to the search state using the ui-router. However, my mapStateToThis function isn't run. I believe this is because the Store technically hasn't changed. The `vm.search` will be an empty String instead of `cow`.

Do I need to bootstrap components to give them to latest data from the store? Perhaps via $onInit?

Example:
```javascript
vm.$onInit = $onInit;

function $onInit()
{
	var stateMap = mapStateToThis($ngRedux.getState())
	vm = Object.assign(vm, stateMap);
}
```

I've tested and it works, but... not sure if I should be doing this. Reckon it's ok since it's part of the Angular 1.5 component lifecycle, but I haven't compared to this to the ngRedux 2, so maybe it's different?

**Comment by wbuchwalter** [comment]
Hey,
`mapStateToThis` will be called once when the component is initialized regardless if the state changed or not.
[Here is the relevant code](https://github.com/angular-redux/ng-redux/blob/master/src/components/connector.js#L43).

Can't really tell why it would not work in your case, but it should :)
Try investigating a bit, and if you can't find why maybe create a plunkr with your code so I can take a look.

**Comment by JesterXL** [comment]
Thanks for the confirmation! Ok, I'll debug, give me a bit.

**Comment by JesterXL** [comment]
Yep, if everything in the function is scoped correctly, it works, I'm a moron. I forgot to scope the function since I'm not using classes:

```javascript
vm.mapStateToThis = mapStateToThis;
```

You can close this, thanks again!

**Comment by JesterXL** [comment]
... although, I wonder why she doesn't throw an exception... is that in logs? I've got the logger turned on I think.

**Comment by wbuchwalter** [comment]
It happens! Thanks :)
