### ISSUE TITLE
Deeply nested action objects bound to the controller aren't wrapped in a dispatch call.

### ISSUE THREAD

**Issue by hally9k** [angular-redux/ng-redux#95]
I haven't spent too much time looking at this repo but had some issues understanding the following behaviour:

When binding a multi level nested object containing actions to a controller the resulting functions on the scope are just the raw action functions and require dispatching manually as opposed to what I assume is happening with less complex action objects which is that each action is being pre wrapped before being bound to the scope.

Could we have some sort of recursive tree walk to wrap all the actions with dispatch regardless of the action object's depth? That would get rid of any ambiguity around whether the action has been wrapped or not... ? Comments?

**Comment by hally9k** [comment]
I cam to the conclusion that I should just flatten my action objects on registering with the controller...

**Comment by wbuchwalter** [comment]
Hey,
Sorry forgot to answer :)
Yes, that was my suggestion too.
Or keeping it as a tree but passing `actionTree.todoAction` to your controller's connect.
