### ISSUE TITLE
Action triggered with "undefined" type

### ISSUE THREAD

**Issue by Nighthawk14** [angular-redux/ng-redux#96]
Hi,

I'm using ng-redux in combination with redux-thunk and have a really simple action doing some asynchronous stuff. The problem is that each time I trigger an action from a controller, I have a "undefined" action dispatched:
<img width="891" alt="screen shot 2016-07-18 at 1 21 34 pm" src="https://cloud.githubusercontent.com/assets/2417908/16905553/026ce234-4ceb-11e6-8bac-1926f0220203.png">

After a bit of digging I think the issue is coming from the fact that the actions passed into  the connect method in the controller are wrapped with the redux `bindActionCreators`. So redux will dispatch what the action returns (e.g. the method taking `dispatch` as an argument) and then we have our "undefined" action. I tried by calling `$ngRedux.dispatch(asyncAction())` but we have the same thing.

Redux is checking if the argument passed in bindActionCreators is an object or a function but not if the result of this argument is a function as well (which seems fine). So, I know that this is not particularly an issue with ng-redux but I mostly wants some points of view on that if possible :).

ps: I tried the basic example redux + redux-thunk and by calling `dispatch(asyncAction())` we don't have this undefined action.

Thanks!

**Comment by matt328** [comment]
+1 I'm seeing the same behavior.  I've registered my action as a service in angular, and am seeing the extra functions bound.

I am also not able to determine what is different from the example async project, my code is pretty much equivalent to that.

**Comment by matt328** [comment]
If you are using this form to create your store:

`$ngReduxProvider.createStoreWith(reducers, middlewares, enhancers);`

thunk has to be first in the middlewares array or else you get undefined actions that seem to do nothing at all except clog up the logger.

Can someone clarify is this an older, junkier way of doing this and what is the current recommended way of creating a store with reducers, middlewares and enhancers?

**Comment by Nighthawk14** [comment]
@matt328  Haha I was writing you the same thing :). Yep changing the order fix it. That's weird. Actually for me just changing the order of `thunk` and `logger` fixed it. I could keep another one before them.

**Comment by matt328** [comment]
I guess I should read documentation a little better:

https://github.com/evgenyrodionov/redux-logger#usage

> Logger must be the last middleware in chain, otherwise it will log thunk and promise, not actual actions (#20).

**Comment by Nighthawk14** [comment]
😓
