### ISSUE TITLE
Role angular service with redux

### ISSUE THREAD

**Issue by michalpanek** [angular-redux/ng-redux#97]
I have a question. I haven't found good explanation about that issue.  If I have in my app ng-redux store, should I get the data from backend through the services, and update store from component's controller, or should I call the store for data instead of service, and store get data calling services, which sending requests to backend api, save to self, and inform component's controller about change in state ?

**Comment by wbuchwalter** [comment]
Here is a typical flow:

* User do something 
* The `Controlle`r calls the corresponding `action creator`
* If new data is needed, the `action creator` fetches them (through an angular service typically) and dispatch a first `action` e.g: `GET_DATA_STARTED`. When the data comes back, the action creators dispatch a second `action`: `GET_DATA_COMPLETED`. The payload of this action will be the data returned by the service.

The reason there is two action (you can do differently) is if you want to show a loading indicator while the data is fetching for example.


Look at Redux's doc [(this section specifically)](http://redux.js.org/docs/advanced/AsyncFlow.html) for more info.

**Comment by michalpanek** [comment]
I don't now if I can continue write in this issue, but I try. 

I have question about DI for angular services, and using them in redux actions. 

Suppose we have code of action function: 

`function getSomeImportantData() {
  return function(dispatch) {
    dispatch(getDataStarted());
    **SomeService**.getData().then(response => console.log(response));
  };
}
`

We call service, which is "SomeService", which call api asynchronously, return promise,  etc. Ok, it works when I pass that "SomeService" "reference" by action function's arg like that: 

`
this.getSomeImportantData(this.SomeService);
`
But I don't think is good way to manage this. I think angular's controller (or component's controller) shouldn't know about services, and shouldn't get it reference through DI. I think only redux action function should have access to angular service, and call his functions, like in my example:

`
  SomeService.getData().then(response => do something with response);
`

But, if I am not wrong all about that, what can I pass angular's service reference, by DI or another way, to redux action so that I can use it, call it, or whatever ? I've tried use import statement like that: 
`
import SomeService from '../path/to/serviceclass';

but It doesn't work. 

@wbuchwalter, could you help me with that ?:) I see light at the end of the tunnel. Help me get
come to the end.:)

**Comment by wbuchwalter** [comment]
You can define your actions inside an angular service and use DI there.
Take a look at the async example ([here specifically](https://github.com/angular-redux/ng-redux/blob/master/examples/async/actions/asyncService.js))

**Comment by michalpanek** [comment]
i think is not good approach also. Should this would not be like that?:

**component-controller** _call_ **redux action **.
**redux action** _call_ **angular services** _for data from_ api
**angular service** _return data from_ api _to_ **redux action**
**redux action** _update_ **state* 
**component-controller** _updating ui/whatever should be based on changed_ **state**.

What do you thinks ? Is there a way to gain this approach something ?

**Comment by michalpanek** [comment]
<blockquote class="imgur-embed-pub" lang="en" data-id="a/MxFvj"><a href="//imgur.com/MxFvj"></a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

**Comment by wbuchwalter** [comment]
Yes, I 100% agree with what you say and the image.
That is what I was talking about also.

* You can use dependency injection **inside** an action creator. Look at the async example. Actions are defined inside a service, that means the service has control over what it needs. The component doesn't have to provide anything.

**Comment by michalpanek** [comment]
thanks, I see it now. For now I've  changed angular 1.x service to just simply js function with no $http dependency. I use fetch and polyfill in webpack, but this is other story. thanks again.:)
